layout_spectrum: 0.6935335407033563
typography_spectrum: 0.5589722413569689
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.23889524233527482
  lightness: 0.36935912584885955
  saturation: 0.5228130358736962
  rhythmicContrast: 0.39998253365047276
name: Digital Whalefood
favicon: null
title: Digital Whale Food
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
